using System;
using System.IO;
using System.Text;

using DoomMapGuessr.Helpers;

using IniParser.Model;
using IniParser.Model.Formatting;
using IniParser.Parser;


namespace DoomMapGuessr.Services
{

	public sealed class ApplicationSettings(
		string directoryPath
	) : IEquatable<ApplicationSettings>
	{

		public static ApplicationSettings Shared { get; } = CreateInRoamingAppData().Prepare();

		public string DirectoryPath { get; } = directoryPath;

		public static ApplicationSettings CreateInCommonAppData() =>
			new(Path.Join(Environment.GetFolderPath(Environment.SpecialFolder.CommonApplicationData), "mf366.dev.DoomMapGuessr"));

		public static ApplicationSettings CreateInLocalAppData() =>
			new(Path.Join(Environment.GetFolderPath(Environment.SpecialFolder.LocalApplicationData), "mf366.dev.DoomMapGuessr"));

		public static ApplicationSettings CreateInRoamingAppData() =>
			new(Path.Join(Environment.GetFolderPath(Environment.SpecialFolder.ApplicationData), "mf366.dev.DoomMapGuessr"));

		public void Clear()
		{

			foreach (string directory in DirectoryPath.EnumerateDirectories())
				Directory.Delete(directory, true);

			foreach (string file in DirectoryPath.EnumerateFiles())
				File.Delete(file);

		}

		public ApplicationSettings Prepare()
		{

			Directory.CreateDirectory(DirectoryPath);

			return this;

		}

		/// <inheritdoc />
		public bool Equals(ApplicationSettings? other)
		{

			if (other is null)
				return false;

			if (ReferenceEquals(this, other))
				return true;

			return DirectoryPath == other.DirectoryPath;

		}

		/// <inheritdoc />
		public override bool Equals(object? obj)
		{

			if (obj is null)
				return false;

			if (ReferenceEquals(this, obj))
				return true;

			return obj.GetType() == GetType() && Equals((ApplicationSettings)obj);

		}

		/// <inheritdoc />
		public override int GetHashCode() => DirectoryPath.GetHashCode();

		public IniData GetResourceFile(string name)
		{

			string path = Path.Join(DirectoryPath, $"{name}.ini");

			if (!File.Exists(path))
				File.WriteAllText(path, "; This file has been auto-generated by DoomMapGuessr", Encoding.UTF8);

			IniDataParser parser = new(
				new()
				{
					AllowCreateSectionsOnFly = true,
					AllowDuplicateKeys = true,
					OverrideDuplicateKeys = true,
					ThrowExceptionsOnError = false
				}
			);

			return parser.Parse(File.ReadAllText(path, Encoding.UTF8));

		}

		public IniData GetResourceFile(string name, IniData defaults)
		{

			string path = Path.Join(DirectoryPath, $"{name}.ini");

			if (!File.Exists(path))
				SetResourceFile(name, defaults);

			IniDataParser parser = new(
				new()
				{
					AllowCreateSectionsOnFly = true,
					AllowDuplicateKeys = true,
					OverrideDuplicateKeys = true,
					ThrowExceptionsOnError = false
				}
			);

			return parser.Parse(File.ReadAllText(path, Encoding.UTF8));

		}

		public void SetResourceFile(string name, IniData resources)
		{

			string path = Path.Join(DirectoryPath, $"{name}.ini");

			string? ini = resources.ToString(
				new DefaultIniDataFormatter(
					new()
					{
						AllowCreateSectionsOnFly = true,
						AllowDuplicateKeys = true,
						OverrideDuplicateKeys = true,
						ThrowExceptionsOnError = false
					}
				)
			);

			File.WriteAllText(path, ini, Encoding.UTF8);

		}

		/// <inheritdoc />
		public override string ToString() => $"{nameof(DirectoryPath)}: {DirectoryPath}";

		public static bool operator ==(ApplicationSettings? left, ApplicationSettings? right) => Equals(left, right);

		public static bool operator !=(ApplicationSettings? left, ApplicationSettings? right) => !Equals(left, right);

	}

}
