//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoomMapGuessr.Strings {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DoomMapGuessr.Strings.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MF366 (Matthew).
        /// </summary>
        public static string AppCreatorName {
            get {
                return ResourceManager.GetString("AppCreatorName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to App Interface.
        /// </summary>
        public static string AppInterface {
            get {
                return ResourceManager.GetString("AppInterface", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to App Language:.
        /// </summary>
        public static string AppLanguageSettingsField {
            get {
                return ResourceManager.GetString("AppLanguageSettingsField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The GeoGuessr of Doom..
        /// </summary>
        public static string AppSlogan {
            get {
                return ResourceManager.GetString("AppSlogan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DoomMapGuessr.
        /// </summary>
        public static string AppTitleName {
            get {
                return ResourceManager.GetString("AppTitleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Follow system theme.
        /// </summary>
        public static string FollowSystemTheme {
            get {
                return ResourceManager.GetString("FollowSystemTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hello, world!.
        /// </summary>
        public static string GreetingText {
            get {
                return ResourceManager.GetString("GreetingText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Follow system.
        /// </summary>
        public static string SameAsSystemOption {
            get {
                return ResourceManager.GetString("SameAsSystemOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dark Mode.
        /// </summary>
        public static string ThemingDarkMode {
            get {
                return ResourceManager.GetString("ThemingDarkMode", resourceCulture);
            }
        }
    }
}
